#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAKA.Bussiness
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KPI")]
	public partial class linqtosqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKPI_Value(KPI_Value instance);
    partial void UpdateKPI_Value(KPI_Value instance);
    partial void DeleteKPI_Value(KPI_Value instance);
    partial void InsertKPI_Calculation_Log(KPI_Calculation_Log instance);
    partial void UpdateKPI_Calculation_Log(KPI_Calculation_Log instance);
    partial void DeleteKPI_Calculation_Log(KPI_Calculation_Log instance);
    partial void InsertKPI(KPI instance);
    partial void UpdateKPI(KPI instance);
    partial void DeleteKPI(KPI instance);
    #endregion
		
		public linqtosqlDataContext() : 
				base(global::SAKA.Bussiness.Properties.Settings.Default.KPIConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public linqtosqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KPI_Value> KPI_Values
		{
			get
			{
				return this.GetTable<KPI_Value>();
			}
		}
		
		public System.Data.Linq.Table<KPI_Calculation_Log> KPI_Calculation_Logs
		{
			get
			{
				return this.GetTable<KPI_Calculation_Log>();
			}
		}
		
		public System.Data.Linq.Table<KPI> KPIs
		{
			get
			{
				return this.GetTable<KPI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KPI_Value")]
	public partial class KPI_Value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _KPI_ID;
		
		private System.DateTime _Date;
		
		private string _Value;
		
		private decimal _Target;
		
		private decimal _Thresholder;
		
		private bool _Thresholder_Type;
		
		private System.DateTime _Creation_Date;
		
		private EntityRef<KPI> _KPI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKPI_IDChanging(System.Guid value);
    partial void OnKPI_IDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    partial void OnTargetChanging(decimal value);
    partial void OnTargetChanged();
    partial void OnThresholderChanging(decimal value);
    partial void OnThresholderChanged();
    partial void OnThresholder_TypeChanging(bool value);
    partial void OnThresholder_TypeChanged();
    partial void OnCreation_DateChanging(System.DateTime value);
    partial void OnCreation_DateChanged();
    #endregion
		
		public KPI_Value()
		{
			this._KPI = default(EntityRef<KPI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid KPI_ID
		{
			get
			{
				return this._KPI_ID;
			}
			set
			{
				if ((this._KPI_ID != value))
				{
					if (this._KPI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKPI_IDChanging(value);
					this.SendPropertyChanging();
					this._KPI_ID = value;
					this.SendPropertyChanged("KPI_ID");
					this.OnKPI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target", DbType="Decimal(12,2) NOT NULL")]
		public decimal Target
		{
			get
			{
				return this._Target;
			}
			set
			{
				if ((this._Target != value))
				{
					this.OnTargetChanging(value);
					this.SendPropertyChanging();
					this._Target = value;
					this.SendPropertyChanged("Target");
					this.OnTargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thresholder", DbType="Decimal(12,2) NOT NULL")]
		public decimal Thresholder
		{
			get
			{
				return this._Thresholder;
			}
			set
			{
				if ((this._Thresholder != value))
				{
					this.OnThresholderChanging(value);
					this.SendPropertyChanging();
					this._Thresholder = value;
					this.SendPropertyChanged("Thresholder");
					this.OnThresholderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thresholder_Type", DbType="Bit NOT NULL")]
		public bool Thresholder_Type
		{
			get
			{
				return this._Thresholder_Type;
			}
			set
			{
				if ((this._Thresholder_Type != value))
				{
					this.OnThresholder_TypeChanging(value);
					this.SendPropertyChanging();
					this._Thresholder_Type = value;
					this.SendPropertyChanged("Thresholder_Type");
					this.OnThresholder_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="Date NOT NULL")]
		public System.DateTime Creation_Date
		{
			get
			{
				return this._Creation_Date;
			}
			set
			{
				if ((this._Creation_Date != value))
				{
					this.OnCreation_DateChanging(value);
					this.SendPropertyChanging();
					this._Creation_Date = value;
					this.SendPropertyChanged("Creation_Date");
					this.OnCreation_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KPI_KPI_Value", Storage="_KPI", ThisKey="KPI_ID", OtherKey="ID", IsForeignKey=true)]
		public KPI KPI
		{
			get
			{
				return this._KPI.Entity;
			}
			set
			{
				KPI previousValue = this._KPI.Entity;
				if (((previousValue != value) 
							|| (this._KPI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KPI.Entity = null;
						previousValue.KPI_Values.Remove(this);
					}
					this._KPI.Entity = value;
					if ((value != null))
					{
						value.KPI_Values.Add(this);
						this._KPI_ID = value.ID;
					}
					else
					{
						this._KPI_ID = default(System.Guid);
					}
					this.SendPropertyChanged("KPI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KPI_Calculation_Log")]
	public partial class KPI_Calculation_Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private System.Guid _KPI_ID;
		
		private System.DateTime _Date;
		
		private string _Exception_Message;
		
		private bool _Success;
		
		private EntityRef<KPI> _KPI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnKPI_IDChanging(System.Guid value);
    partial void OnKPI_IDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnException_MessageChanging(string value);
    partial void OnException_MessageChanged();
    partial void OnSuccessChanging(bool value);
    partial void OnSuccessChanged();
    #endregion
		
		public KPI_Calculation_Log()
		{
			this._KPI = default(EntityRef<KPI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KPI_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid KPI_ID
		{
			get
			{
				return this._KPI_ID;
			}
			set
			{
				if ((this._KPI_ID != value))
				{
					if (this._KPI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKPI_IDChanging(value);
					this.SendPropertyChanging();
					this._KPI_ID = value;
					this.SendPropertyChanged("KPI_ID");
					this.OnKPI_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Exception_Message", DbType="NVarChar(MAX)")]
		public string Exception_Message
		{
			get
			{
				return this._Exception_Message;
			}
			set
			{
				if ((this._Exception_Message != value))
				{
					this.OnException_MessageChanging(value);
					this.SendPropertyChanging();
					this._Exception_Message = value;
					this.SendPropertyChanged("Exception_Message");
					this.OnException_MessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Success", DbType="Bit NOT NULL")]
		public bool Success
		{
			get
			{
				return this._Success;
			}
			set
			{
				if ((this._Success != value))
				{
					this.OnSuccessChanging(value);
					this.SendPropertyChanging();
					this._Success = value;
					this.SendPropertyChanged("Success");
					this.OnSuccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KPI_KPI_Calculation_Log", Storage="_KPI", ThisKey="KPI_ID", OtherKey="ID", IsForeignKey=true)]
		public KPI KPI
		{
			get
			{
				return this._KPI.Entity;
			}
			set
			{
				KPI previousValue = this._KPI.Entity;
				if (((previousValue != value) 
							|| (this._KPI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KPI.Entity = null;
						previousValue.KPI_Calculation_Logs.Remove(this);
					}
					this._KPI.Entity = value;
					if ((value != null))
					{
						value.KPI_Calculation_Logs.Add(this);
						this._KPI_ID = value.ID;
					}
					else
					{
						this._KPI_ID = default(System.Guid);
					}
					this.SendPropertyChanged("KPI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KPI")]
	public partial class KPI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _Name;
		
		private decimal _Target;
		
		private char _Period;
		
		private decimal _Thresholder;
		
		private bool _Thresholder_Type;
		
		private string _Unit;
		
		private bool _Direction;
		
		private System.DateTime _Creation_Date;
		
		private System.Nullable<System.DateTime> _Modification_Date;
		
		private EntitySet<KPI_Value> _KPI_Values;
		
		private EntitySet<KPI_Calculation_Log> _KPI_Calculation_Logs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnTargetChanging(decimal value);
    partial void OnTargetChanged();
    partial void OnPeriodChanging(char value);
    partial void OnPeriodChanged();
    partial void OnThresholderChanging(decimal value);
    partial void OnThresholderChanged();
    partial void OnThresholder_TypeChanging(bool value);
    partial void OnThresholder_TypeChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnDirectionChanging(bool value);
    partial void OnDirectionChanged();
    partial void OnCreation_DateChanging(System.DateTime value);
    partial void OnCreation_DateChanged();
    partial void OnModification_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnModification_DateChanged();
    #endregion
		
		public KPI()
		{
			this._KPI_Values = new EntitySet<KPI_Value>(new Action<KPI_Value>(this.attach_KPI_Values), new Action<KPI_Value>(this.detach_KPI_Values));
			this._KPI_Calculation_Logs = new EntitySet<KPI_Calculation_Log>(new Action<KPI_Calculation_Log>(this.attach_KPI_Calculation_Logs), new Action<KPI_Calculation_Log>(this.detach_KPI_Calculation_Logs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Target", DbType="Decimal(12,2) NOT NULL")]
		public decimal Target
		{
			get
			{
				return this._Target;
			}
			set
			{
				if ((this._Target != value))
				{
					this.OnTargetChanging(value);
					this.SendPropertyChanging();
					this._Target = value;
					this.SendPropertyChanged("Target");
					this.OnTargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Char(1) NOT NULL")]
		public char Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thresholder", DbType="Decimal(12,2) NOT NULL")]
		public decimal Thresholder
		{
			get
			{
				return this._Thresholder;
			}
			set
			{
				if ((this._Thresholder != value))
				{
					this.OnThresholderChanging(value);
					this.SendPropertyChanging();
					this._Thresholder = value;
					this.SendPropertyChanged("Thresholder");
					this.OnThresholderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thresholder_Type", DbType="Bit NOT NULL")]
		public bool Thresholder_Type
		{
			get
			{
				return this._Thresholder_Type;
			}
			set
			{
				if ((this._Thresholder_Type != value))
				{
					this.OnThresholder_TypeChanging(value);
					this.SendPropertyChanging();
					this._Thresholder_Type = value;
					this.SendPropertyChanged("Thresholder_Type");
					this.OnThresholder_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="NVarChar(MAX)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="Bit NOT NULL")]
		public bool Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Creation_Date", DbType="Date NOT NULL")]
		public System.DateTime Creation_Date
		{
			get
			{
				return this._Creation_Date;
			}
			set
			{
				if ((this._Creation_Date != value))
				{
					this.OnCreation_DateChanging(value);
					this.SendPropertyChanging();
					this._Creation_Date = value;
					this.SendPropertyChanged("Creation_Date");
					this.OnCreation_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modification_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Modification_Date
		{
			get
			{
				return this._Modification_Date;
			}
			set
			{
				if ((this._Modification_Date != value))
				{
					this.OnModification_DateChanging(value);
					this.SendPropertyChanging();
					this._Modification_Date = value;
					this.SendPropertyChanged("Modification_Date");
					this.OnModification_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KPI_KPI_Value", Storage="_KPI_Values", ThisKey="ID", OtherKey="KPI_ID")]
		public EntitySet<KPI_Value> KPI_Values
		{
			get
			{
				return this._KPI_Values;
			}
			set
			{
				this._KPI_Values.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KPI_KPI_Calculation_Log", Storage="_KPI_Calculation_Logs", ThisKey="ID", OtherKey="KPI_ID")]
		public EntitySet<KPI_Calculation_Log> KPI_Calculation_Logs
		{
			get
			{
				return this._KPI_Calculation_Logs;
			}
			set
			{
				this._KPI_Calculation_Logs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KPI_Values(KPI_Value entity)
		{
			this.SendPropertyChanging();
			entity.KPI = this;
		}
		
		private void detach_KPI_Values(KPI_Value entity)
		{
			this.SendPropertyChanging();
			entity.KPI = null;
		}
		
		private void attach_KPI_Calculation_Logs(KPI_Calculation_Log entity)
		{
			this.SendPropertyChanging();
			entity.KPI = this;
		}
		
		private void detach_KPI_Calculation_Logs(KPI_Calculation_Log entity)
		{
			this.SendPropertyChanging();
			entity.KPI = null;
		}
	}
}
#pragma warning restore 1591
